//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableConvertTests.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableConvertTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ||1||2||3||4||5||6||7||8||9||10||11||12||13||14||15||
        ///|\_|\-|\:|\?|\.|\(|\)|\{|\}|\*|\\|\#|\^|\+|\~|
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpectedJira001 {
            get {
                return ResourceManager.GetString("ExpectedJira001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   |1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|
        ///|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
        ///|\_|\-|\!|\.|\(|\)|\[|\]|\{|\}|\*|\\|\#|\`|\+|
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpectedMarkdown001 {
            get {
                return ResourceManager.GetString("ExpectedMarkdown001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
        ///a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,
        ///p,q,r,s,t,u,v,w,x,y,z,aa,ab,ac,ad, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpectedTable001 {
            get {
                return ResourceManager.GetString("ExpectedTable001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
        ///_,-,:,?,.,(,),{,},*,\,#,^,+,~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputJira001 {
            get {
                return ResourceManager.GetString("InputJira001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
        ///_,-,!,.,(,),[,],{,},*,\,#,`,+ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputMarkdown001 {
            get {
                return ResourceManager.GetString("InputMarkdown001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ||1||2||3||4||5||6||7||8||9||10||11||12||13||14||15|| ||
        ///|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o| |
        ///|p|q|r|s|t|u|v|w|x|y|z|aa|ab|ac|ad| | に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableJira001 {
            get {
                return ResourceManager.GetString("TableJira001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   |1|2|3|4|5|6|7|8|9|10|11|12|13|14|15| |
        ///|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o| |
        ///|p|q|r|s|t|u|v|w|x|y|z|aa|ab|ac|ad| | に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableJira002 {
            get {
                return ResourceManager.GetString("TableJira002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +---+---+---+---+---+---+---+---+---+----+----+----+----+----+----+--+
        ///| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 |  |
        ///+---+---+---+---+---+---+---+---+---+----+----+----+----+----+----+--+
        ///| a | b | c | d | e | f | g | h | i | j  | k  | l  | m  | n  | o  |  |
        ///| p | q | r | s | t | u | v | w | x | y  | z  | aa | ab | ac | ad |  |
        ///+---+---+---+---+---+---+---+---+---+----+----+----+----+----+----+--+ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableLattice001 {
            get {
                return ResourceManager.GetString("TableLattice001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   |1|2|3|4|5|6|7|8|9|10|11|12|13|14|15||
        ///|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
        ///|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o||
        ///|p|q|r|s|t|u|v|w|x|y|z|aa|ab|ac|ad|| に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableMarkdown001 {
            get {
                return ResourceManager.GetString("TableMarkdown001", resourceCulture);
            }
        }
    }
}
